services:
  - type: web
    name: heimdals-horn-webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: OPENAI_API_KEY
        value: sk-...
      - key: OPENAI_ASSISTANT_ID
        value: asst-...
      - key: BALDR_WEBHOOK_URL
        value: ""
      - key: AUTOGEN_WEBHOOK_URL
        value: ""