services:
  - type: web
    name: heimdals-horn-webhook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: "./start.sh"
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY