services:
  - type: web
    name: heimdals-horn-webhook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn webhook.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY